### ISSUE TITLE
fetching key_pairs

### ISSUE THREAD

**Issue by alek-thunder** [mi-1-0-0/openstack-neo4j-service#6]
The does not contain the public keys of all OpenStack users.

**Comment by alek-thunder** [comment]
Which seem to not be intended directly. Lets remove the "key_pair" node type completely from the graph DB for now

https://specs.openstack.org/openstack/nova-specs/specs/liberty/implemented/admin-query-any-keypair.html

**Comment by muhammad-i-imran** [comment]
Removed key_pairs from the config, but its code is still in place (in case we need it later).
