### ISSUE TITLE
Neo4JApi.find_relationship is broken

### ISSUE THREAD

**Issue by ekeih** [mi-1-0-0/openstack-neo4j-service#7]
The `py2neo.matching.RelationshipMatcher.match()` function is called with wrong parameters at https://github.com/mi-1-0-0/cloud-reconnoiterer/blob/master/graph_service_api/neo4japi/neo4japi.py#L267. According to https://py2neo.org/v4/matching.html#py2neo.matching.RelationshipMatcher the `source_node` and `target_node` have to be passed as one parameter. One solution could be to pass `source_node + target_node` as one list of both nodes. But I am not 100% sure if this would actually do what you intended with the function.

**Comment by muhammad-i-imran** [comment]
Thanks for raising the issue. `py2neo.matching.RelationshipMatcher.match()`  function requires a sequence or set as `nodes` parameter. If we want to ignore the direction of the relationship then set is required, or else a sequence can be used. I will push the fix and publish the new docker images soon.

**Comment by muhammad-i-imran** [comment]
The latest images containing the fix for the issue (along with the merged pull requests) have been published. The images' version is 1.6.

**Comment by ekeih** [comment]
Thanks :)

**Comment by muhammad-i-imran** [comment]
you are welcome!
